version: "3.7"

services:

  webapp-queue:
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-fhir-mapper_rabbit_1:15672", "--", "python", "receive.py"]
    build:
      context: .
    depends_on:
      - rabbit
    environment:
      - FHIR_SERVER_ADDRESS=romanova
      - REQUESTS_CA_BUNDLE=consult.crt
    extra_hosts:
      # If fhir server at IP rather than known host, name on fhir server's certificate : fhir server IP.
      romanova: 192.168.99.101
    tty: true

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    volumes:
      - ehr_data_volume:/var/lib/rabbitmq

volumes:
  ehr_data_volume:

networks:
  default:
    name: ehr_network
