version: "3.7"

services:

  webapp-queue:
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-fhir-mapper_rabbit_1:15672", "--", "python", "receive.py"]
    build:
      context: .
    depends_on:
      - rabbit
    environment:
      - FHIR_SERVER_ADDRESS=romanova:8080
      - FHIR_SERVER_USERNAME=consult
      - FHIR_SERVER_PASSWORD=consultproject2017
      - REQUESTS_CA_BUNDLE=consult.crt
    extra_hosts:
      # Gateway of fhir_network. Acts as entry point into network like a docker machine hostname.
      romanova: 172.20.0.1
    tty: true

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    volumes:
      - ehr_data_volume:/var/lib/rabbitmq

volumes:
  ehr_data_volume:

networks:
  default:
    name: ehr_network
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
