version: "3.7"

services:

  webapp-queue:
    build:
      context: .
    command: ["./wait-for-it/wait-for-it.sh", "rabbit:15672", "--", "python", "receive.py"]
    depends_on:
      - rabbit
    links:
      - rabbit

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
    volumes:
      - ehr_data_volume:/var/lib/rabbitmq

volumes:
  ehr_data_volume:

networks:
  default:
    name: network
